version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: sh -c 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    env_file:
      - ./.docker.env
  redis:
    image: redis:alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025
  celery:
    build:
      context: .
    command: celery -A _core worker -Q celery --loglevel=INFO
    env_file:
      - ./.docker.env
    depends_on:
      - app
      - redis
volumes:
  agenda-db:
